//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COSA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int Id { get; set; }
        public string Mensaje1 { get; set; }
        public int CostoId { get; set; }
        public long EmisorId { get; set; }
        public int ChatId { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual Costos Costos { get; set; }
        public virtual Telefonos Telefonos { get; set; }
    }
}
